/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InsertionSort */

#ifndef _Included_InsertionSort
#define _Included_InsertionSort
#ifdef __cplusplus
extern "C" {
#endif
#undef InsertionSort_MIN_PRIORITY
#define InsertionSort_MIN_PRIORITY 1L
#undef InsertionSort_NORM_PRIORITY
#define InsertionSort_NORM_PRIORITY 5L
#undef InsertionSort_MAX_PRIORITY
#define InsertionSort_MAX_PRIORITY 10L
/*
 * Class:     InsertionSort
 * Method:    memoryAccessesAndSortedArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_InsertionSort_memoryAccessesAndSortedArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
